[basic]
name = "level-1"

[graphic]
bg-file = "assets/bg-0.png"
bg-color-rgb = "204, 237, 255"

[level]
def = """
#.......[].............................................................................................................#
#.......[].............................................................................................................#
#.......[].............................................................................................................#
#.......[].............................................................................................................#
#.......[].............................................................................................................#
#.......[].............................................................................................................#
#.......[].............................................................................................................#
#.......[].............................................................................................................#
#.......[].............................................................................................................#
#.......[].............................................................................................................#
#.......<>.............................................................................................................#
#.......H..............................................................................................................#
#......................................................................................................................#
#......................................................................................................................#
#......................................................................................................................#
#......................................................................................................................#
#............................................................................................................{}........#
#............................................................................................................[]........#
#............................................................................................................[]........#
GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG
gggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggg
gggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggg
"""

dec-def = """
........................................................................................................................
........................................................................................................................
........................................................................................................................
........................................................................................................................
........................................................................................................................
........................................................................................................................
........................................................................................................................
........................................................................................................................
........................................................................................................................
........................................................................................................................
........................................................................................................................
........................................................................................................................
........................................................................................................................
........................................................................................................................
........................................................................................................................
........................................................................................................................
........................................................................................................................
........................................................................................................................
........................................................................................................................
........................................................................................................................
........................................................................................................................
........................................................................................................................
"""

[transfer]
next-levels = ["level-1"]