[basic]
name = "level-0.secret-0"

[graphic]
bg-file = "assets/bg-0.png"
bg-color-rgb = "0, 0, 0"

[level]
def = """
BBBBBBBBBBBBBBBBBBBBBBBBBBBBB
B..H........................B
B...........................B
B...........................B
B...........................B
BBBBBBBBBBBBBBBBBBBB........B
B...........................B
B...........................B
B...........................B
B...........................B
B.....BBBBBBBBBBBBBBBBBBBBBBB
B...........................B
B...........................B
B...........................B
B...........................B
BBBBBBBBBBBBBBBBBBBB........B
B...........................B
B...........................B
B...{}......................B
B...[]......................B
B...[]......................B
BBBBBBBBBBBBBBBBBBBBBBBBBBBBB
"""

dec-def = """
.............................
.............................
.............................
.............................
.............................
.............................
.............................
.............................
.............................
.............................
.............................
.............................
.............................
.............................
.............................
.............................
.............................
.............................
.............................
.............................
.............................
.............................
"""

[transfer]
next-levels = ["level-0"]