[basic]
name = "level-0"

[graphic]
bg-file = "assets/bg-0.png"
bg-color-rgb = "204, 237, 255"

[level]
def = """
BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
B##..........[].......................................................................................................BB
B##..........[].......................................................................................................BB
B##..........[].......................................................................................................BB
B##..........[].......................................................................................................BB
B##..........[].......................................................................................................BB
B##..........[].......................................................................................................BB
B##..........[].......................................................................................................BB
B##..........[].......................................................................................................BB
B##..........[].......................................................................................................BB
B##..........[].......................................................................................................BB
B##..........[].......................................................................................................BB
B##..........[].......................................................................................................BB
B##..........[].......................................................................................................BB
B##..........[].......................................................................................................BB
B##..........[].......................................................................................................BB
B##..........[]..........LGGR.........................................................................................BB
B##..........[]..........lggr.........BBBB............................................................................BB
B##..........<>..........lggr.........................................................................................BB
B##..........H..........LGGGGGR.......................................................................................BB
B##...BB................lgggggr.......................................................................................BB
B##.....................lgggggr..........CCM.............."..1..."....................................................BB
B##......{}...........LGGGGGGGGR...()......................BBBBBB......ccc.............{}.............................BB
B##......[]......1....lggggggggr...[]..2.......B.......................................[].............................BB
B##......[]...........lggggggggr...E].........BBBB.....................ccc.............[].............................BB
BGGGGGGGGGGGGGGGGGGR.LGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG...GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGBB
Bggggggggggggggggggr.lgggggggggggggggggggggggggggggggggggggggggWWWggggggggggggggggggggggggggggggggggggggggggggggggggggBB
Bggggggggggggggggggr.lgggggggggggggggggggggggggggggggggggggggggwwwggggggggggggggggggggggggggggggggggggggggggggggggggggBB
"""

dec-def = """
........................................................................................................................
........................................................................................................................
........................................................................................................................
........................................................................................................................
........................................................................................................................
........................................................................................................................
........................................................................................................................
........................................................................................................................
........................................................................................................................
........................................................................................................................
........................................................................................................................
........................................................................................................................
........................................................................................................................
........................................................................................................................
........................................................................................................................
........................................................................................................................
........................................................................................................................
........................................................................................................................
........................................................................................................................
........................................................................................................................
........................................................................................................................
........................................................................................................................
........................................................................................................................
........................................................................................................................
..........1.............................................................................................................
------------------------------------------------------------------------------------------------------------------------
------------------------------------------------------------------------------------------------------------------------
------------------------------------------------------------------------------------------------------------------------
"""

[transfer]
next-levels = ["level-0.secret-0", "level-1"]