[basic]
name = "level-0"
next-level-name = "level-0"

[graphic]
bg-file = "assets/bg-0.png"
bg-color-rgb = "204, 237, 255"

[level]
def = """
BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
B##..........[].......................................................................................................BB
B##..........[].......................................................................................................BB
B##..........[].......................................................................................................BB
B##..........[].......................................................................................................BB
B##..........[].......................................................................................................BB
B##..........[].......................................................................................................BB
B##..........[].......................................................................................................BB
B##..........[].......................................................................................................BB
B##..........[].......................................................................................................BB
B##..........[].......................................................................................................BB
B##..........[].......................................................................................................BB
B##..........[].......................................................................................................BB
B##..........[].......................................................................................................BB
B##..........[].......................................................................................................BB
B##..........[].......................................................................................................BB
B##..........[].......................................................................................................BB
B##..........[].......................BBBB............................................................................BB
B##..........<>.......................................................................................................BB
B##..........H........................................................................................................BB
B##...BB..............................................................................................................BB
B##......................................CCM.............."..1..."....................................................BB
B##........................................................BBBBBB...............{}....................................BB
B##..............1.......BBB...........2.......B................................[]....................................BB
B##...LGR..............BBBBBBBBB..............BBBB..............................[]....................................BB
BGGGGGIIIGGGGGGGGGGG.GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG...GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGBB
BIIIIIIIIIIIIIIIIIII.IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIWWWIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIBB
BIIIIIIIIIIIIIIIIIII.IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIwwwIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIBB
"""

dec-def = """
........................................................................................................................
........................................................................................................................
........................................................................................................................
........................................................................................................................
........................................................................................................................
........................................................................................................................
........................................................................................................................
........................................................................................................................
........................................................................................................................
........................................................................................................................
........................................................................................................................
........................................................................................................................
........................................................................................................................
........................................................................................................................
........................................................................................................................
........................................................................................................................
........................................................................................................................
........................................................................................................................
........................................................................................................................
........................................................................................................................
........................................................................................................................
........................................................................................................................
........................................................................................................................
........................................................................................................................
..........1.............................................................................................................
------------------------------------------------------------------------------------------------------------------------
------------------------------------------------------------------------------------------------------------------------
------------------------------------------------------------------------------------------------------------------------
"""
