[basic]
name = "level-0"

[graphic]
bg-file = "assets/bg-0.png"
bg-color-rgb = "204, 237, 255"

[level]
def = """
BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
B##..........[].......................................................................................................BB
B##..........[].......................................................................................................BB
B##..........[].......................................................................................................BB
B##..........[].......................................................................................................BB
B##..........[].......................................................................................................BB
B##..........[].......................................................................................................BB
B##..........[].......................................................................................................BB
B##..........[].......................................................................................................BB
B##..........[].......................................................................................................BB
B##..........[].......................................................................................................BB
B##..........[].......................................................................................................BB
B##..........[].......................................................................................................BB
B##..........[].......................................................................................................BB
B##..........[].......................................................................................................BB
B##..........[].......................................................................................................BB
B##..........[]........LGGGGR.........................................................................................BB
B##..........[]........lggggr.........BBBB............................................................................BB
B##..........<>........lggggr.........................................................................................BB
B##..........H.........lgLGGGGGR......................................................................................BB
B##...BB...............lglgggggr......................................................................................BB
B##....................lglgggggr.........CCM.............."..1..."....................................................BB
B##......{}...........LGGGRggggr...()......................DDDDDD......ccc.............{}.............................BB
B##......[]......1....lgggrggggr...[]..2.......B.......................................[].............................BB
B##......[]...........lgggrggggr...E].........BBBB.....................ccc.............[].............................BB
BGGGGGGGGGGGGGGGGGGR.LGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG...GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGBB
Bggggggggggggggggggr.lgggggggggggggggggggggggggggggggggggggggggWWWggggggggggggggggggggggggggggggggggggggggggggggggggggBB
Bggggggggggggggggggr.lgggggggggggggggggggggggggggggggggggggggggwwwggggggggggggggggggggggggggggggggggggggggggggggggggggBB
"""

dec-def = """
........................................................................................................................
........................................................................................................................
........................................................................................................................
........................................................................................................................
........................................................................................................................
........................................................................................................................
........................................................................................................................
........................................................................................................................
........................................................................................................................
........................................................................................................................
........................................................................................................................
........................................................................................................................
........................................................................................................................
........................................................................................................................
........................................................................................................................
........................................................................................................................
........................................................................................................................
........................................................................................................................
........................................................................................................................
........................................................................................................................
........................................................................................................................
........................................................................................................................
........................................................................................................................
........................................................................................................................
..........1.............................................................................................................
------------------------------------------------------------------------------------------------------------------------
------------------------------------------------------------------------------------------------------------------------
------------------------------------------------------------------------------------------------------------------------
"""

[transfer]
next-levels = ["level-1", "level-0.secret-0"]